#!/bin/bash
set -ex


GOBIN=$(go env GOBIN)
export GOBIN=$GOBIN

go get -v github.com/google/go-licenses

mkdir -p "${PREFIX}/share/go-licenses"
cp \
  "${GOPATH:-"$( go env GOPATH )"}"/pkg/mod/github.com/google/licenseclassifier*/licenses/licenses.db \
  "${PREFIX}/share/go-licenses/"

go-licenses save . --save_path=./thirdparty-licenses
> thirdparty-licenses.txt cat <<'EOF'
The output below is generated by `go-licenses csv` and `go-licenses save`.
--------------------------------------------------------------------------------
EOF
>> ./thirdparty-licenses.txt go-licenses csv .
>> ./thirdparty-licenses.txt find ./thirdparty-licenses -type f -printf '

--------------------------------------------------------------------------------
%P
================================================================================
' -exec cat {} \;
